### ISSUE TITLE
Report does not have all the features when the sharding is set to true

### ISSUE THREAD

**Issue by sri85** [igniteram/protractor-cucumber-allure#13]
@igniteram When i try to run the tests in parallel using shards it looks like the generated report just has the last run feature file . In short the cucumber.json file is overridden when the `shards:true`

**Comment by igniteram** [comment]
Yes, there is a known issue with sharding and cucumber json, let me find that issue no. for more details!

**Comment by sri85** [comment]
@igniteram I did the changes as mentioned here https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/pull/19 , basically creating json file separately for each feature file using `multiCapabilities` and then using `jsonDir` option in `cucumber-html-reporter` to merge all the json files in to a single one and  create a html report from the consolidated html report . Its a workaround

**Comment by igniteram** [comment]
Yup. that's a work around for now but in future there might a better way of doing it! closing this issue as of now.

**Comment by sri85** [comment]
Maybe i will raise a PR for this

**Comment by igniteram** [comment]
Sure you are always welcome for it! :+1:
