### ISSUE TITLE
Screenshot is not captured

### ISSUE THREAD

**Issue by pnakhat** [igniteram/protractor-cucumber-allure#18]
When a test fails it doesn't capture screenshot

**Comment by igniteram** [comment]
Can you please be more specific & mention what you tried? As it is very difficult to debug with your current info.

**Comment by pnakhat** [comment]
I made one of the step failed and expected screenshot to be captured in the scenario report. In fact I tried putting console.log in the hooks , doesn't seems like hooks getting triggered at all.

**Comment by igniteram** [comment]
This is also fixed with new cucumber 2 changes, the error screenshots are attached with the reports as well as generated individually.

**Comment by igniteram** [comment]
closing this issue as haven't heard back on this from the issuer.
