### ISSUE TITLE
Upgrade to ES6 syntax!

### ISSUE THREAD

**Issue by igniteram** [igniteram/protractor-cucumber-allure#23]

**Comment by paulohfcanuto** [comment]
@igniteram 
I'm using your model to write the tests of an angular application, I'm writing the tests in ES6 and some classes to help load elements on the screen, classes to map the pages receiving the screen elements as the parameter of the test cases, just the config.js is not in ES6, for now I'm using require ('babel-register'); in the onPrepare function inside the config.js, I intend to generate a bundle with the wepack in the future, if you want I can share the code ...

**Comment by igniteram** [comment]
@paulohfcanuto that would be awesome! In fact you could send in a pull request. Users would definitely benefit from that. As far as transpiler like babel is considered I have used Typescript for that purpose in my other repo. But this repo is quite old and needs some love :) We could definitely switch to ES6 faster by a transpiler and since you have already used babel , it would be a useful PR. Looking forward for your contribution 👍

**Comment by igniteram** [comment]
Closing this issue with https://github.com/igniteram/protractor-cucumber-allure/pull/33 merged!
