### ISSUE TITLE
No report generated if assertion fails on title comparison

### ISSUE THREAD

**Issue by chit786** [igniteram/protractor-cucumber-allure#25]
## Steps ##

Just replace Google in homepage.js with Google123 to reproduce this.

## Expected ##

Should capture the screenshot and generate the report.

Can you please guide me here whats missing.

![image](https://user-images.githubusercontent.com/18376182/30775265-70eb0142-a090-11e7-99fc-a31f3ff75d78.png)

**Comment by chit786** [comment]
I am able to handle this by , `ignoreUncaughtExceptios:true` , in config, but this does not completely solve the problem, as I am also expecting a screenshot, which is not working and getting a timeout in After hook. Any thoughts? 

~Thanks
![image](https://user-images.githubusercontent.com/18376182/30780557-d6ee2aaa-a10d-11e7-838d-485c3ba7d4b6.png)

**Comment by chit786** [comment]
Hi , 
```

  After({ timeout: 20 * 1000 },function(scenario) {
    if (scenario.isFailed()) {
       var attach = this.attach; // cucumber's world object has attach function which should be used
      return browser.takeScreenshot().then(function(png) {
        var decodedImage = new Buffer(png, "base64");
        return scenario.attach(decodedImage, "image/png");
      });
    }
  });

```

modified After hook like this solves the timeout problem, 

but then received following error : 
![image](https://user-images.githubusercontent.com/18376182/30782051-a0900c2c-a12a-11e7-99cb-88ec25a84cd9.png)


Strangely browser.takeScreenshot() is not working . chrome version : Version 60.0.3112.11

**Comment by igniteram** [comment]
@chit786 Can you please specify the versions of following modules which you are using in your project?

* protractor
* cucumber
* protractor-cucumber-framework

So that I could debug this specific issue!

**Comment by chit786** [comment]
@igniteram  thank you for reverting.

Well, I just cloned your repo and trying to run it as per my expectations! just checking for how the screenshots gets appended, but unfortunately, not able to see the screenshot working.

> {
  "name": "protractor-cucumber-allure",
  "version": "1.0.0",
  "license": "MIT",
  "description": "To demostrate protractor cucumber tests for angular/non angular apps with allure report framework",
  "homepage": "https://github.com/igniteram/protractor-cucumber-allure",
  "keywords": [
    "protractor",
    "cucumber",
    "allure reports",
    "angular",
    "angularjs",
    "testing",
    "behaviour driven development",
    "bdd",
    "selenium",
    "webdriverJS",
    "posgreSQL",
    "gherkin",
    "automation testing"
  ],
  "main": "index.js",
  "scripts": {
    "test": "protractor config/config.js",
    "webdriver-start": "webdriver-manager start",
    "webdriver-update": "webdriver-manager update"
  },
  "author": "Ram Pasala <ram.pasala7@gmail.com>",
  "dependencies": {
    "chai": "^4.0.2",
    "cucumber": "^2.3.0",
    "mkdirp": "^0.5.1",
    "protractor": "^5.1.1",
    "protractor-cucumber-framework": "^3.1.0"
  },
  "devDependencies": {
    "chai-as-promised": "^6.0.0",
    "cucumber-html-report": "^0.6.0",
    "cucumber-html-reporter": "^0.5.2",
    "cucumberjs-allure-reporter": "^1.0.3",
    "pg": "^6.0.3"
  },
  "repository": "https://github.com/igniteram/protractor-cucumber-allure"
}

I have not changed as such anything, just npm install after cloning.

Also observed one thing that , 

> onPrepare: function() {
>     browser.ignoreSynchronization = true;
>     **//browser.manage().window().maximize();**
>     global.expect = chai.expect;
>   },

I had to comment this window.maximize in this version of webdriver.

I am running protractor globally. with below characteristics of chrome driver and selenium webdriver.

![image](https://user-images.githubusercontent.com/18376182/30783510-4ecd61e0-a144-11e7-9d99-782ad718a26d.png)

The problem I am seeing is with the `takeScreenshot` function of the `browser` which is not able to consume `browser` object.

but when I did console.log(typeof browser) It correctly gave me object type, in After hook. So trying to figure out what am I missing here.

Thanks again.

**Comment by chit786** [comment]
Well.. I tried again . this time locally and not global protractor. on local package protractor version I am getting chromedriver version as 2.32 and that is working fine.. so closing this issue. I believe it has something to do with the chromedriver version . 

Thanks for this amazing work.

**Comment by chit786** [comment]
Also do you have any plans of working on allure report ? Cheers.

**Comment by igniteram** [comment]
Glad it worked! currently [cucumberjs-allure-reporter](https://github.com/allure-framework/allure-cucumberjs) doesn't support cucumber 2.x version onwards and sadly that repo isn't active anymore. So someone has to raise a PR or create a new repo for support of new cucumber versions with allure. I would love to work on it if I get time but considering my work commitments I can't assure though  :)
