### ISSUE TITLE
browser.restart with Page object pattern do not work

### ISSUE THREAD

**Issue by chit786** [igniteram/protractor-cucumber-allure#26]
Hi again! 

I am facing a problem when trying to implement a restart between scenarios.

Changes I done : 

 registerHandler("**BeforeScenario**", { timeout: 10 * 1000 }, function() {
        return browser.get(conf.baseUrl);
    });

After(function(scenario) {
        if (scenario.isFailed()) {
            var attach = this.attach; // cucumber's world object has attach function which should be used
            return browser.takeScreenshot().then(function(png) {
                var decodedImage = new Buffer(png, "base64");
                attach(decodedImage, "image/png");
                **return browser.restart();**
            })
        }
    });

And this restarts the browser between tests, but strangely I am getting exception same as mentioned in this ticket : 

**https://github.com/angular/protractor/issues/3595**

Can you please help here to understand what's happening. And how I can utilie the world object as explained in above solution (if really thats the only option )

I really want to close the browser in case of failure of the tests.

**Comment by igniteram** [comment]
Hi, are you still facing this issue? if yes which version of protractor, cucumber and protractor-cucumber-framework are you using?

**Comment by chit786** [comment]
@igniteram  sorry was a bit off radar. but upgrading to new cucumber worked , so there I am no more using registerHandler. 

Cucumber > v 3
protractor = 5.1.2

**Comment by igniteram** [comment]
@chit786 Thanks for confirming! closing this issue !

**Comment by rakhmatullov** [comment]
I still have exactly the same issue.
Progractor version = 5.4.2
Cucumber version = 6.0.5
