### ISSUE TITLE
Chrome Driver Execution: Error message: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.

### ISSUE THREAD

**Issue by BHARATSEHRA** [igniteram/protractor-cucumber-allure#6]
Hi Ram,

Script is not getting executed on changing the browser in config.js from "firefox" to "chrome". 
The issue here was that you need to specify the path to your selenium jar and chrome driver exe in your protractor config file. Mine was installed globally in AppData folder so i have mentioned the path of both the variables i.e chrome driver and selenium standalone server in config.js  and things started working for me as expected. 
OR 
Copy the selenium folder from the AppData folder and place it within the solution explorer under "protractor-cucumber-allure-master\node_modules\protractor\node_modules\webdriver-manager".

**Comment by igniteram** [comment]
Yes, you could do it by giving the chrome driver path or you could do a local webdriver-manager update, which would install the chrome driver locally in your project folder, the reason it was not detecting was you installed it globally, one thing you could do is webdriver-manager update directly from the binary file which comes along with protractor module installed locally!

Closing this as it is a support question!
